[acolyt]
author_github = "TxCorpi0x"
author_wallet = ""

[aixbt]
author_github = "bluntbrain"
author_wallet = "0x3cdd051eeC909f94965F9c1c657f5b70a172B2C0"

[allora]
author_github = "TxCorpi0x"
author_wallet = ""

[cdp]
author_github = "hyacinthus"
author_wallet = "0x445750026A4a1906b61302442E085f9cbAfe206a"

[common]
author_github = "hyacinthus"
author_wallet = "0x445750026A4a1906b61302442E085f9cbAfe206a"

[cryptocompare]
author_github = "0xkieranwilliams"
author_wallet = "0x91D43BfDc698b1e510efa0811e2e07F628D02e6b"

[cryptopanic]
author_github = "v1ktorrr0x"
author_wallet = "0x178741Fc5BA9B77147398853c28736eEFe5fCff1"

[dapplooker]
author_github = "bluntbrain"
author_wallet = "0x3cdd051eeC909f94965F9c1c657f5b70a172B2C0"

[defillama]
author_github = "0xkieranwilliams"
author_wallet = "0x91D43BfDc698b1e510efa0811e2e07F628D02e6b"

[elfa]
author_github = "TxCorpi0x"
author_wallet = ""

[enso]
author_github = "TxCorpi0x"
author_wallet = ""

[github]
author_github = "bluntbrain"
author_wallet = "0x3cdd051eeC909f94965F9c1c657f5b70a172B2C0"

[goat]
author_github = "TxCorpi0x"
author_wallet = ""

[heurist]
author_github = "hyacinthus"
author_wallet = "0x445750026A4a1906b61302442E085f9cbAfe206a"

[moralis]
author_github = "developerfred"
author_wallet = ""

[nation]
author_github = "spidemen"
author_wallet = ""

[openai]
author_github = "hyacinthus"
author_wallet = "0x445750026A4a1906b61302442E085f9cbAfe206a"

[slack]
author_github = "hyacinthus"
author_wallet = "0x445750026A4a1906b61302442E085f9cbAfe206a"

[tavily]
author_github = "bluntbrain"
author_wallet = "0x3cdd051eeC909f94965F9c1c657f5b70a172B2C0"

[twitter]
author_github = "hyacinthus"
author_wallet = "0x445750026A4a1906b61302442E085f9cbAfe206a"

[unrealspeech]
author_github = "bluntbrain"
author_wallet = "0x3cdd051eeC909f94965F9c1c657f5b70a172B2C0"

[unrealspeech]
author_github = "yornfifty"
author_wallet = "0xF60D4B6780D5D51827602D7aC319458bc9e921F4"
